language: node_js
cache:
  directories:
    - "node_modules"
node_js:
  - "11"
script:
  - yarn
  - mv packages/upswyng-native/config.example.ts packages/upswyng-native/config.ts
  - yarn run ci-lint
  - yarn run test
