language: node_js
cache:
  directories:
    - "node_modules"
node_js:
  - "11"
script:
  - npm run bootstrap
  - mv packages/upswyng-native/config.example.ts packages/upswyng-native/config.ts
  - npm run ci-lint
  - lerna run test
