version: "3.7"
services:
  mongo:
    container_name: upswyng-dev-db
    image: mongo:3.6.20
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: local
      MONGO_INITDB_DATABASE: upswyng-dev
    volumes:
      - ./packages/server/localdb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  mongo-express:
    container_name: upswyng-mongo-express
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: local
  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
